# Site settings
title: Wonga Technology
email: jobs@wonga.com
description: > # this means to ignore newlines until "baseurl:"
  Wonga Technology
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://wongatech.github.io" # the base hostname & protocol for your site
twitter_username: wongatech
github_username:  wongatech
highlighter: pygments

# Build settings
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]

# Author info
authors:
  wojciechkotlarski:
    display_name: Wojciech Kotlarski
    github: Suremaker
  bengodfrey:
    display_name: Ben Godfrey
    github: afternoon
  paulbourke:
    display_name: Paul Bourke
    github: brk3
  edconolly:
    display_name: Ed Conolly
    github: edconolly
  julienwetterwald:
    display_name: Julien Wetterwald
    github: julienwetterwald
  carlpearse:
    display_name: Carl Pearse
  ronshteinberg:
    display_name: Ron Shteinberg
