# Site settings
title: Wonga Technology
email: jobs@wonga.com
description: > # this means to ignore newlines until "baseurl:"
  Wonga Technology
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://wongatech.github.io" # the base hostname & protocol for your site
twitter_username: wongatech
github_username:  wongatech
highlighter: pygments

# Build settings
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]

# Author info
authors:
  wojciechkotlarski:
    display_name: Wojciech Kotlarski
    gravatar: d5390c88bd988bfe08dfa51c5e45ed48
    github: Suremaker
  bengodfrey:
    display_name: Ben Godfrey
    gravatar: c3649388fd9af95667fc2fde3aac7938
    github: afternoon
    twitter: afternoon
  paulbourke:
    display_name: Paul Bourke
    gravatar: 59adba2d05b317af2443f27e761f44a4
    github: brk3
    twitter: brk3
