# Site settings
title: wongatech
email: jobs@wonga.com
description: > # this means to ignore newlines until "baseurl:"
  Wonga Technology Blog
baseurl: "http://wongatech.github.io" # the subpath of your site, e.g. /blog/
url: "http://wongatech.github.io" # the base hostname & protocol for your site
twitter_username: wongatech
github_username:  wongatech
highlighter: pygments

# Build settings
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
