# Site settings
title: wongatech
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "http://wongatech.github.io" # the subpath of your site, e.g. /blog/
url: "http://wongatech.github.io" # the base hostname & protocol for your site
twitter_username: wongatech
github_username:  wongatech
highlighter: pygments

# Build settings
markdown: kramdown
